// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAqfFwc6SBhMZNX7PnPV-FeiTrKiaQM1Ps',
//     appId: '1:171879978457:web:8aefc64a73f1c6f1f0f5c8',
//     messagingSenderId: '171879978457',
//     projectId: 'vibes-ddb6d',
//     authDomain: 'vibes-ddb6d.firebaseapp.com',
//     storageBucket: 'vibes-ddb6d.appspot.com',
//     measurementId: 'G-4HJ7R8ETQR',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCBQcHyJlbpQ71Uj6lXJapm9bRuHgQBkXw',
//     appId: '1:171879978457:android:04a076eb3b91feeaf0f5c8',
//     messagingSenderId: '171879978457',
//     projectId: 'vibes-ddb6d',
//     storageBucket: 'vibes-ddb6d.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCE2j4k8H5jNo8KLROnYvK_ewvlPdoSDaU',
//     appId: '1:171879978457:ios:05286ad5491e3dc4f0f5c8',
//     messagingSenderId: '171879978457',
//     projectId: 'vibes-ddb6d',
//     storageBucket: 'vibes-ddb6d.appspot.com',
//     iosBundleId: 'com.example.vibe',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCE2j4k8H5jNo8KLROnYvK_ewvlPdoSDaU',
//     appId: '1:171879978457:ios:05286ad5491e3dc4f0f5c8',
//     messagingSenderId: '171879978457',
//     projectId: 'vibes-ddb6d',
//     storageBucket: 'vibes-ddb6d.appspot.com',
//     iosBundleId: 'com.example.vibe',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAqfFwc6SBhMZNX7PnPV-FeiTrKiaQM1Ps',
//     appId: '1:171879978457:web:d3bef5c896be7cdff0f5c8',
//     messagingSenderId: '171879978457',
//     projectId: 'vibes-ddb6d',
//     authDomain: 'vibes-ddb6d.firebaseapp.com',
//     storageBucket: 'vibes-ddb6d.appspot.com',
//     measurementId: 'G-F6GJD0P08B',
//   );
// }
